### ISSUE TITLE
Firebase & Google log-in instructions snag

### ISSUE THREAD

**Issue by jonathantmiles** [LambdaSchool/ios-lambda-timeline#1]
I recommend reminding the student in Part One, Step 4 to enable the Google sign in by clicking the toggle slider in the table of available log-ins. 

It's easy to miss, since one's attention is drawn to the fields in that drop-down menu. Without toggling the setting here, the app won't advance past the first storyboard, even though it appears to log in to Google correctly. 

The error that led me to catch this does get logged in the console, but a gentle reminder here would be great.

**Comment by PaulSolt** [comment]
Updated thanks @jonathantmiles
